// Mocks generated by Mockito 5.0.16 from annotations
// in unit_testing_sample/test/widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:unit_testing_sample/network/http_client.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponse_0 extends _i1.Fake implements _i2.Response {}

/// A class which mocks [MyHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyHttpClient extends _i1.Mock implements _i3.MyHttpClient {
  MockMyHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> get({Map<String, String>? params}) =>
      (super.noSuchMethod(Invocation.method(#get, [], {#params: params}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i4.Future<_i2.Response>);
  @override
  _i4.Future<_i2.Response> post<T>(String? endpointUrl, T? body) =>
      (super.noSuchMethod(Invocation.method(#post, [endpointUrl, body]),
              returnValue: Future<_i2.Response>.value(_FakeResponse_0()))
          as _i4.Future<_i2.Response>);
  @override
  String toString() => super.toString();
}
